FROM node as build
WORKDIR /app
COPY ./ ./
RUN npm install
RUN npm run storybook:build

FROM nginx
WORKDIR /etc/nginx
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/storybook-static /usr/share/nginx/html



