FROM node:current-alpine as build
WORKDIR /app
COPY ./ ./
RUN npm ci
RUN npm run storybook:build

FROM nginx:1.23.1-alpine
# WORKDIR /etc/nginx
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/storybook-static /usr/share/nginx/html



